name: CI Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest # Операционная система для выполнения job'а

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest # Операционная система для выполнения job'а

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Test
        run: npm run test
